version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: '12:00'
    timezone: Europe/Moscow
  open-pull-requests-limit: 99
  reviewers:
  - gpchelkin
  assignees:
  - gpchelkin

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: '12:00'
    timezone: Europe/Moscow
  open-pull-requests-limit: 99
  reviewers:
  - gpchelkin
  assignees:
  - gpchelkin
