deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: gpchelkin
  password:
    secure: !!binary |
      Q2J2dExBU2l6bDFlam9oL3ZSNng4V2JHOFMwamVLMHZFcnp6WjhUZnA5QmFSa0kvemt5cUVlemUr
      L29aeFZCSWNGQ0JJWlNlVnVzQi9ObkVLMkVKaHNUczgvTWROR0M4d29sZE9YamVhbVM3TTRxNHRV
      bUg1L1lHMGZBN09IR1d2ZS9Rajh3MTRIc2Q1a3QwTW9yWlFaaUE3bDY3aHhGVVY3dmQ0QXlvNTdG
      UGQ2VlRSU2djMXVDK0FHaDlCWVVBSVFYZkd1Z2pvNHM3MHMxVGZJZHkwSWh0aWhmRjgxL3lSeGov
      bFdGZUh5dFN0eG1QYWhLNFdqWmhkQnluVXhyRmV3L205V3JwSEN0TytBc3VnS3psaUU1UCs3REEv
      dXVZOEw0RWMwOUZmNnNtdlNPaFNWUFR5ckNLMU96MWR1elVNSTltN3lCM0hBNjNzS1lHM2pjYWxs
      K21Jakc5U1BDRlZtNGg2bG1RQWthVklLNFVkUnhva2tFQ2YrQ3kzRmdkemlhR2JCQ0pyQ1VNcjY5
      Y2xESXY1Y1YzZTdYOGZDTXdEeUxUSGNuVlBrRFYwclY1V2ZYQUhYOUdIbWRyWEtYanNwWk9aU1cr
      OXZtVVhWZlVFdGR5RVcxa3ZtYUtGYVMrYjVUeU1IQnFNOGFDNHp1OFFwQWJwVDRXNlJOd1BJMFpF
      TjVHZ2NySHhYb1NvTWtpc0ZtTkNBdDU2VXlOYXRiemNhcy9JYkpmM3ZvTi9mNUthak01MHluM0hi
      TEFPclVZcEVrMWRvTm1ySlFSTVFRTXRraXdSODJDcGYrdGhpbGJua2lEVUQ3Zy91bks4S1FuRXZh
      MWNweXZkN1M2enJHUnorMFBQYUVSQjJKaHZZRjE0TU15TmxYTWdrNWd2cHIvOTBVM0xQeE5oQXM9
  true:
    python: 3.6
    repo: gpchelkin/scdlbot
    tags: true
install: pip install -U tox-travis
language: python
python:
- 3.6
- 3.5
- 3.4
script: tox
