name: build

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install tox and poetry
      run: |
        # pipes do not work in GitHub Actions #TODO
        # pip freeze | xargs pip uninstall -y
        pip install --upgrade pip setuptools tox tox-gh-actions
        export POETRY_VERSION=1.1.12
        wget "https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py"
        python "install-poetry.py"

    - name: Test with tox
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        poetry config installer.parallel false
        poetry config experimental.new-installer false
        # poetry config virtualenvs.in-project true
        cat "$HOME/.config/pypoetry/config.toml"
        export PATH="$(pwd)/.venv/bin:$PATH"
        tox
