name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2.3.1
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.1.1
      with:
        python-version: ${{ matrix.python-version }}

#TODO pipes do not work in GitHub Actions
#        "pip freeze | xargs pip uninstall -y"

    - name: Install tox and poetry
      run: |
        pip install --upgrade pip tox tox-gh-actions
        wget "https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py"
        python "get-poetry.py"

    - name: Test with tox
      run: |
        source "$HOME/.poetry/env"
        tox
